### ISSUE TITLE
Update Datastore Security Rule

### ISSUE THREAD

**Issue by bakisunsan** [Ryukyo/Kodokura#95]
The firestore can be used in test mode for up to 30 days, after which it will be inaccessible if the correct security rules are not updated.

https://firebase.google.com/docs/rules/basics

**Comment by Ryukyo** [comment]
Should be no problem. I already changed the rule when we set up Firestore:
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if
          request.time < timestamp.date(2020, 12, 31);
    }
  }
}

So for now, reads and writes are allowed for the rest of the year
